### ISSUE TITLE
Product input fields or the custom field is not displayed on invoice, delivery notes or receipt.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#114]
The client has an issue where the product input fields value and the custom field value is not displayed on the invoice, delivery notes or receipt.

Screenshots:  
1) https://prnt.sc/qcfmll
2) https://prnt.sc/qcfng3

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/11660

**Comment by mokshasharmila13** [comment]
The custom field value from the Product input fields plugin is now displayed on the invoice, delivery notes & receipts properly.

![Screenshot from 2022-02-28 12-09-58](https://user-images.githubusercontent.com/81163257/155936262-b5decb01-c7cf-43d0-a996-d553d41d495c.png)
