### ISSUE TITLE
Include New Hooks Added in print-content.php template file 

### ISSUE THREAD

**Issue by kartikparmar** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#118]
These hooks were added when doing customization for the below ticket.
Ticket: https://tychesoftwares.freshdesk.com/helpdesk/tickets/15109

This client wanted to hide the address section and add one table and the bottom he wanted to display the information which was coming from 'Checkout Field Editor for WooCommerce'.

[print-content.zip](https://github.com/TycheSoftwares/woocommerce-delivery-notes/files/4473428/print-content.zip)

**Comment by mokshasharmila13** [comment]
This issue is fixed by customizing as per the client's requirement.
