### ISSUE TITLE
Shipping Address doesn’t print if different than billing

### ISSUE THREAD

**Issue by dhruvins** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#121]
If a customer has the same billing and shipping addresses, both addresses will print on an invoice or delivery note. However, when the addresses are different, it only prints the billing. We need the opposite or just have both always print would be fine.

Related forum: https://wordpress.org/support/topic/shipping-address-doesnt-print-if-different-than-billing/

**Comment by kenil802** [comment]
One more client has faced this issue.

Link: https://wordpress.org/support/topic/shipping-delivery-addresses-not-showing/

**Comment by kenil802** [comment]
One more client has the same issue.

Link: https://wordpress.org/support/topic/shipping-address-not-showing-2/

**Comment by kenil802** [comment]
Another client has the same issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22519
