### ISSUE TITLE
Attributes not coming in the Invoice/Delivery Note

### ISSUE THREAD

**Issue by dhruvins** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#124]
Create a variable product with a custom attribute “Size” with “Small | Medium | Large”.

Place an order with these variations and print an order. These custom attributes are not coming in the Delivery Note and Invoice

Related Forum: https://wordpress.org/support/topic/not-showing-all-attributes-after-the-last-wordpress-update/

**Comment by Shasvat7** [comment]
With the latest copy, I am not able to replicate this issue hence closing it.
Screenshot of the invoice where attributes coming properly: https://www.awesomescreenshot.com/image/10752510?key=b04bd3cb2ae1bd667c82cbc5b05f152b
