### ISSUE TITLE
Able to display labels for billing and shipping address 

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#135]
The client wants the feature that should display labels for the billing and shipping address.

Link: https://wordpress.org/support/topic/display-labels-for-billing-and-shipping-address/

**Comment by kenil802** [comment]
Another client wants the same.

Link: https://wordpress.org/support/topic/display-labels-for-billing-shipping-address/

**Comment by kenil802** [comment]
One more client wants the same.

Link: https://wordpress.org/support/topic/write-labels-for-shipping-and-billing-address/

**Comment by apeksha10** [comment]
After taking the latest git copy, the invoice, delivery note, and receipt do not display any labels.

https://www.screencast.com/t/qawQ8jTEKGGP

Plugin settings: https://www.screencast.com/t/VvVXfGRcyMRW

Hence -re-open this issue

**Comment by mokshasharmila13** [comment]
Fixed this issue and labels are added to our invoice
