### ISSUE TITLE
print-content.php needs to account for item meta that are PHP classes

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#144]
The client suggested that:
templates/print-order/print-content.php has a check for whether the item_meta is an array and skips it if true, but some plugins (e.g, Woocommerce Partial Orders Pro) store PHP classes in item meta resulting in a PHP fatal error in those cases.

There are multiple ways to prevent the fatals, but one would be to replace lines 164-166 with:

if ( ! is_string( $value ) ) {
	if ( is_object( $value ) && method_exists( $value, '__toString' ) ) {
		$value = strval( $value );
	} else {
		continue;
	}
}

Link: https://wordpress.org/support/topic/print-content-php-needs-to-account-for-item-meta-that-are-php-classes/#post-13380274

**Comment by mokshasharmila13** [comment]
This issue is old and no other client has asked this type of requirement in our plugin
