### ISSUE TITLE
Bulk printing is not working with 4.6.2 version

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#172]
**Describe the bug**
The client has reported the issue where the bulk printing is not working with the latest version of the plugin 4.6.2

**To Reproduce**
1) Select a few orders from the Orders Page.
2) In the bulk actions option, click on the Print Invoice.
3) You will see the blank page.

**Expected behavior**
The bulk printing of the invoice should work.

**Additional context**
The issue has been reported by the client whereas I am unable to replicate the same issue.

Link: https://wordpress.org/support/topic/bulk-printing-not-working-in-4-6-2/

**Comment by kenil802** [comment]
Another client is facing the same issue.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25080

**Comment by kenil802** [comment]
One more client has reported the same.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25149

**Comment by Shasvat7** [comment]
With the latest copy, I am not able to replicate this issue, hence I am closing it.
Video for the same: https://www.awesomescreenshot.com/video/4510302?key=c7c5aa48e9fdc8216f5b4ebd1fcfa7ec
