### ISSUE TITLE
The checkout page load continuously and the plugin does not allow me to place an order.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#180]
**Describe the bug**
The checkout page load continuously and the plugin does not allow me to place an order.

1. PHP 8.0 set up
2. Take the latest live copy that is 4.6.2
3. Add the product
4. Go to the checkout page, but the checkout page loads continuously and the plugin does not allow me to place an order
see the screenshot: https://www.screencast.com/t/VIEcj61Ei

**Expected behavior**
The checkout page load should not loads continuously and the plugin should allow me to place an order.

**Comment by Shasvat7** [comment]
@apeksha10 I have checked this issue with PHP 8.0.7, but I am not able to replicate it. 
Here's the video for the same: https://www.awesomescreenshot.com/video/4510017?key=e8d27fc817a498c75801c7c8852acf76
So please check and let me know about it.
