### ISSUE TITLE
Print invoice shows some notice when I click the Print button on the order received page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#201]
**Describe the bug**
Print invoice shows some notice when I click the Print button on the order received page. 

**To Reproduce**
1. Take the latest live copy. 
2. Orddd lite copy also activate on my local (v3.16.1)
2. Placed an order
3. Click on the Print button on the Order received page, I got some notice. see the screenshot : https://www.screencast.com/t/ywEFUTcnMJcg

**Expected behavior**
No errors must be thrown from our plugin.

**Comment by mokshasharmila13** [comment]
While clicking on the print button on the order received page it is not showing any notice or error, Orddd lite copy was also activated and checked.

![Screenshot from 2022-02-24 12-29-40](https://user-images.githubusercontent.com/81163257/155475568-ebf0b165-06c3-4716-bab2-7605ca637292.png)
