### ISSUE TITLE
Incompatible with ‘High-Performance order storage'

### ISSUE THREAD

**Issue by mokshasharmila13** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#230]
Our plugin needs to be compatible with "High-Performance order storage " in woo-commerce.

Issue Link:- https://wordpress.org/support/topic/compatibility-with-high-performance-order-storage-3/
Screenshot:- https://prnt.sc/qKQgSzmSHF84.

**Comment by oluisrael11** [comment]
Another user requested for this - [https://tychesoftwares.freshdesk.com/a/tickets/56671](https://tychesoftwares.freshdesk.com/a/tickets/56671)

**Comment by upenkapse** [comment]
Another user has asked for this: https://wordpress.org/support/topic/hpos-compatibility-55/

**Comment by upenkapse** [comment]
A couple of users have asked for iit here: https://wordpress.org/support/topic/hpos-compatibility-32/

**Comment by rashmimalpande** [comment]
Tested and released in 4.8.0
