### ISSUE TITLE
Prints Invoice, Delivery Note, and Receipt icons are missing on the woo_order page. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#235]
**Describe the bug**
Prints Invoice, Delivery Note, and Receipt icons are missing on the woo_order page. 

**To Reproduce**
1. Upload the latest git copy 
2. Go to the Woo-order page, I notice that Prints Invoice, Delivery Note, and Receipt icons are missing. https://app.screencast.com/mONH3KBApOFNM

**Expected behavior**
Prints Invoice, Delivery Note, and Receipt icons should be present on the woo_order page.

**Comment by mital-tyche** [comment]
There is not any missing icons.
Here is screenshot for your reference.
https://prnt.sc/dAtgHylRxwqK

**Comment by gaminikhil** [comment]
There are no missing icons in the order-page.
Here is a screenshot for your reference.
[https://prnt.sc/RfyMchT8KgJY](https://prnt.sc/RfyMchT8KgJY)
Hence, I am closing this issue.
