### ISSUE TITLE
The print buttons are missing on the order detail screen.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#236]
**Describe the bug**
The print buttons are missing on the order detail screen.

**To Reproduce**
1. Upload the latest git copy 
2. Place an order 
3. Go to the Edit order page, I notice print buttons are missing. https://app.screencast.com/qvNiNJpD2nPX8

Live copy. https://app.screencast.com/txnIxVN3LqgLx (order printing box is missing in latest copy)

**Expected behavior**
The print buttons should be available on the order detail screen.

**Comment by mital-tyche** [comment]
Print button display proper in order edit page.
Also we  need to check 'Order Printing' checkbox'.
https://prnt.sc/pfUdNYmi9XA6

Additionally we need to enabled or disabled these option in print setting tab in woocommerce setting page
https://prnt.sc/QASK4qJdmHTk
Here is screenshot for your reference.
https://prnt.sc/B4x1QnhHRsU8

**Comment by gaminikhil** [comment]
It is working: [https://prnt.sc/mMg_U7seWXYL](https://prnt.sc/mMg_U7seWXYL) hence, I am closing this issue.
