### ISSUE TITLE
Clicked on the "print" button plugin from the order received page the plugin redirected me to the My Account page. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#237]
**Describe the bug**
Clicked on the "print" button plugin from the order received page the plugin redirected me to the My Account page. 

**To Reproduce**
1. Taking the latest copy 
2. Place an order 
3. Go to the woo_order page, clicking on the 'Print' button, it redirects to the My Account page.  https://app.screencast.com/0wsdheVddzcEo

**Expected behavior**
The plugin should redirect to the correct page.

**Comment by apeksha10** [comment]
Thank you for your order email has the same above issue. when I clicked on the Print button it redirects me to the My Account page. https://app.screencast.com/mUVQWrtJ1Vhz7

**Comment by apeksha10** [comment]
Show print button on View Order page/ Show print button on My Account page feature also redirects me on My Account page when I clicked on Print button from Order received page and My Account page.

**Comment by gaminikhil** [comment]
It is working properly. Hence, I am closing this issue.
