### ISSUE TITLE
Can we assign other name instead of Documents ?

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#244]
**Describe the bug**
Can we assign another name instead of Documents?

Documents contain information, facts, or data

If you're suggesting that the name "Documents" section may mislead users into thinking it contains actual documents when it doesn't, you could consider alternative names that provide clearer expectations

Let me know your thought

**Comment by upenkapse** [comment]
We can rename the Documents title to **Templates**: https://prnt.sc/DY-9VDgyIaKg 

@geogirish what do you think?

**Comment by geogirish** [comment]
Hi @upenkapse 

Yes, "Templates" makes sense. 
What exactly do we show in Invoice, Receipts, and Delivery Notes?
