### ISSUE TITLE
The invoice number appears to be one number ahead.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#248]
**Describe the bug**
The invoice number appears to be one number ahead.

**To Reproduce**
1. Invoice setup. https://app.screencast.com/AjY32017zV5hi
2. Place an order 
3. Go to the woo_order page, clicked on the 'Print Invoice' image, the invoice number appears to be one number ahead. 
https://app.screencast.com/Mnel7Vd9f4rPU

**Expected behavior**
The invoice number appears should not be one number ahead.

**Comment by gaminikhil** [comment]
It is working properly for me. Hence, I am closing this issue.
