### ISSUE TITLE
"Unknow" text appears on the pdf file with the default invoice setup. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#249]
**Describe the bug**
"Unknow" text appears on the pdf file with the default invoice setup. 

1. Invoice Setup https://app.screencast.com/00pHG30FpkBlr, https://app.screencast.com/mtrXCpt8uwrVs
2. Place an order 
3. New Order email received fine 
4. Open the PDF file, I notice that "Unknow" text appears and the Shop logo is missing.
https://app.screencast.com/b4ynHQx8rdo6r

Logo setup. https://app.screencast.com/DSKyRLJHLHrMP

When I clicked the Print Invoice button on the woo_order page then things are working fine. https://app.screencast.com/jGmfNtBR85ntS

**Expected behavior**
The shop logo should appear in the PDF file.

**Comment by mital-tyche** [comment]
https://prnt.sc/3CZCrwoMVktn
The logo appears properly in every PDF

**Comment by gaminikhil** [comment]
[https://prnt.sc/E67FVCQtmv80](https://prnt.sc/E67FVCQtmv80)
It is working properly, hence I am closing this issue.
