### ISSUE TITLE
The email address is missing in the customize pdf receipt file even though the email address is enabled. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#258]
**Describe the bug**
The email address is missing in the customized pdf receipt file even though the email address is enabled. 

**To Reproduce**
1. Customize Receipt setup. https://app.screencast.com/8NsrS6ly65nhJ
3. Place an order 
4. Email received fine
5. But the customized receipt pdf file does not show the email address. https://app.screencast.com/7rhmcuMw6QRxx

**Expected behavior**
The email address should appear in the customized pdf receipt file

**Comment by mital-tyche** [comment]
Hello @apeksha10 ... Can you please again check this one or give me access of your site..
https://prnt.sc/g4UiVnVPOKcb 
email is display fine on my side.

**Comment by pinalj** [comment]
@apeksha10 - pls reopen this issue if it is replicated in round 2.
