### ISSUE TITLE
Security issue: able to view customer invoices without being that customer or logged in.

### ISSUE THREAD

**Issue by jordanhenderson** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#296]
It is currently possible to view/print customer invoices without being logged in as the same customer for the order.

**To Reproduce**
1. Visit the 'print-order' endpoint directly, ie. <your-site>/my-account/print-order/123456/ or /my-account/print-order/123456/?print-order-type=invoice&print-order-email=<customer-email>
2. The invoice is rendered, even if not logged in or logged in as a completely different customer.

**Expected behavior**
A 404/empty page should be rendered if the customer is not logged in and should have access to this order.

**Screenshots or Video**
Simply visit the link with incognito. This issue could lead to invoices being publicly indexed, which is a major security issue.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only WooCommerce Print Invoice & Delivery Note plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**Additional context**
This occurs as there are no security checks on the template_redirect_theme function within class-wcdn-print.php.
A suggested fix is to add the below:
```
                $order_id = $wp->query_vars['print-order'];
                $order = wc_get_order($order_id);
                if(!is_user_logged_in() || (get_current_user_id() != $order->get_customer_id())) {
                    $wp_query->set_404();
                    status_header( 404 );
                    get_template_part( 404 );
                    exit;
                }

```

**Comment by mokshasharmila13** [comment]
This issue is not replicated. I tried testing it by logging in with a customer's username, placing an order, and then accessing the myaccount/print-order link using a different email ID. However, the page was blank, and I couldn't see any details. Therefore, it seems that the information is not visible to other customers. I have tested this by checking both the live copy and the Github copy.
