### ISSUE TITLE
Payment Received stamp is not working in receipt templates setting

### ISSUE THREAD

**Issue by gaminikhil** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#316]
**Describe the bug**

The payment Received stamp is not working in the order print receipt [button](https://prnt.sc/SGG2yhXTzU4l). need to fix this.

It is properly working for PDF files.
Screenshort- [https://prnt.sc/Z9N_0_YBv876](https://prnt.sc/Z9N_0_YBv876)

**Comment by mokshasharmila13** [comment]
The payment received stamps function is currently working as intended. Please note that this function is only functional when attaching PDFs to emails on the admin and customer sides. We have not added any code to the admin side's print receipt link, and I believe that the payment received stamp is unnecessary for the admin side's print receipt function.

[Received_receipt.pdf](https://github.com/TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce/files/14649472/Received_receipt.pdf)

**Comment by gaminikhil** [comment]
It is not showing properly in the admin order print receipt  [https://prnt.sc/LSsJpbmwHLvw](https://prnt.sc/LSsJpbmwHLvw).
Reference screenshot short: [https://prnt.sc/n0huQNJCQdqm](https://prnt.sc/n0huQNJCQdqm).
