### ISSUE TITLE
Disable all the field when the default template is selected 

### ISSUE THREAD

**Issue by mokshasharmila13** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#322]
**Is your feature request related to a problem? Please describe.**
When selecting the default type, we need to retrieve all fields to be disabled and add a notice/description. For the simple type, it should function as provided.

Screenshot:- https://tinyurl.com/28v7y96a

**Comment by mokshasharmila13** [comment]
This issue has been resolved after adding the necessary code during UI changes implementation.

**Comment by apeksha10** [comment]
In the latest version, when the Default template is selected, users are unable to click on fields such as the company logo, company address, billing address, and shipping address. I believe this is how we implemented it.
