### ISSUE TITLE
Some filters are missing in the simple receipt.

### ISSUE THREAD

**Issue by gaminikhil** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#327]
**Describe the bug**
Some filters are missing in the simple receipt template. I have noticed that the code is missing in the simple receipt template. That's why the filter is not applied to the receipt template.

Filters name: wcdn_order_item_product, wcdn_order_item_before, wcdn_order_item_after

**Comment by mokshasharmila13** [comment]
Chetna:- I have not worked with Chetna didi much but she is very helpful
