### ISSUE TITLE
The values of the variable product when added to the bundle product are not displayed on the invoice or on the delivery note.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#86]
**Describe the bug**
The values of the variable product when added to the bundle product are not displayed on the invoice or on the delivery note.

Bundle product is created using YITH WooCommerce Product Bundles Premium plugin.

**To Reproduce**
1. Create a bundle product which does include the variable product.
2. Place a order where the variant of the variable product is selected.
3. See the error, the value of the variant is not shown in the Invoice or on the Delivery Note.

**Screenshots or Video**
https://prnt.sc/nye3n1 , https://prnt.sc/nye3zq , https://prnt.sc/nye47o
 
Every plugin is updated, WooCommerce 3.6.4, WordPress 5.2.1, Print invoice 4.4.8

Plugin: https://www.dropbox.com/s/2xoam6jeco8sby0/yith-woocommerce-product-bundles-premium.zip?dl=0

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/8391

**Comment by mokshasharmila13** [comment]
This is an old issue and no other client has this type of issue in our plugin.
