### ISSUE TITLE
Some errors are found in the debug log file.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#87]
**Describe the bug**
Some errors are found in the debug log file on client site: https://tychesoftwares.freshdesk.com/a/tickets/9135

https://www.screencast.com/t/jcnHjzQDN79

**Comment by kenil802** [comment]
Another client reported the same issue.

Link: https://wordpress.org/support/topic/erros-in-log-2/

**Comment by kenil802** [comment]
One more client has the same issue.

Link: https://wordpress.org/support/topic/errors-in-log-10/
