### ISSUE TITLE
Nonce verification error is displayed for multiple files when making compliant with WPCS

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#90]
**Describe the bug**
Nonce verification error is displayed in multiple files of the plugin when we are making it compliant with WPCS standards. This needs to be reviewed & fixed.

If we know we are going to ignore those nonce errors, then we need to write a // phpcs:ignore above it. If not, then we need to fix & add the nonce where required.

**Comment by mokshasharmila13** [comment]
Closing this issue now, whenever needed  will comply with WPCs
